name: MongoDB Insertion

on:
  push:
    branches:
      - main

jobs:
  insert_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo

      - name: Run insertion script
        run: python scripts/insert_data.py
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          DATABASE: your_database_name
          COLLECTION: your_collection_name
          FILENAME: path/to/your/json_file.json
